# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aba387dbe4269b4d37483718afc192f31c5cd8439516b89d3ca0f229e4fcd9d73611631161c593a4e3d897f3877b07f46c0a8e608c23632b08f5b579556efed4

test:
  secret_key_base: 32effb0b3fc2aeebdc188bbb015124643b8108bcfdc8e6ea7a38c13ad78580b08a75d7bfe8d48dd3be9f383fbf41e26a30f8f736b6d3dc6354b963bc8278b028

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
